//login
export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL';
export const USER_LOGOUT='USER_LOGOUT';

//signup
export const USER_SIGNUP_REQUEST='USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS='USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL='USER_SIGNUP_FAIL'

//application

// export const APPLY_REQUEST='APPLY_REQUEST'
// export const APPLY_SUCCESS='APPLY_SUCCESS'
// export const APPLY_FAIL='APPLY_FAIL'
